# PR-3: Holistic Data Preparer

## Part-A: Conceptual Foundation

(1) Write a Short note on:

1. What is Data Analysis?
- Data Analysis is the process of collecting, cleaning, organizing, and examining data to discover useful information and support decision-making.

- Steps of Data Analysis:
    1. Collect data
    2. Clean the data
    3. Explore the data
    4. Analyze the data
    5. Visualize the results
    6. Make decisions based on findings

2. How to Plan a Data Science Project.
- A Data Science project should follow a structured process.

- Steps:
    1. Define the business problem.
    2. Collect data from different sources.
    3. Clean and preprocess the data.
    4. Explore the data using statistics and visualization.
    5. Build machine learning models.
    6. Evaluate model performance.
    7. Deploy the model.
    8. Monitor and improve the model.

3. How to Frame a Machine Learning Problem.
- Framing a machine learning problem involves understanding the business context and translating it into a data-driven question.

- Steps:
    1. Identify the problem.
    2. Define the target variable.
    3. Select input features.
    4. Choose the ML type:
        - Classification
        - Regression
        - Clustering
    5. Collect and prepare data.
    6. Select an evaluation metric.
    7. Train and test the model.

(2) Explain Tensors and provide an in-depth explanation with NumPy examples.
- Tensors are multi-dimensional arrays that generalize scalars, vectors, and matrices. They are fundamental data structures in machine learning and deep learning frameworks.
- In NumPy, tensors can be represented using `numpy.ndarray`.
- Example of creating tensors in NumPy:

```python
import numpy as np

scalar = np.array(5)
print(scalar)
print(scalar.ndim)  
```
```python

vector = np.array([1, 2, 3])
print(vector)
print(vector.ndim) 
```
```python

matrix = np.array([[1, 2], [3, 4]])
print(matrix)
print(matrix.ndim) 
```
```python

tensor_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(tensor_3d)
print(tensor_3d.ndim)  
```

## Part-B: Data Acquisition

3. Import datasets from multiple sources (CSV, JSON, API)

In [2]:
import pandas as pd
Data = pd.read_csv("customer_credit_risk_dataset.csv")
Data.head()

,customer_id,age,gender,region,education_level,employment_type,annual_income,loan_amount,loan_purpose,credit_score,repayment_history,transaction_count,spending_ratio,join_date,default_flag
0,1,NaN,Female,North,Primary,Salaried,1077610.09,664785.70,Car,700.8,11,461,56.36,2024-08-15,0
1,2,NaN,Female,East,Primary,Salaried,807240.03,564159.13,Business,687.7,10,364,56.32,2020-06-21,0
2,3,NaN,Other,West,Primary,Self-Employed,663601.61,NaN,Home,734.8,5,438,39.24,2020-12-19,0
3,4,56.0,Male,South,Graduate,Salaried,875676.45,40513.55,Car,574.6,5,300,26.34,2018-10-12,1
4,5,27.0,Other,South,Secondary,Salaried,459448.99,587944.74,Business,714.2,10,141,69.65,2025-08-31,1

In [3]:
import json

with open("customer_metadata.json", "r") as f:
    customer_data = json.load(f)
    print(customer_data)

[{'customer_id': 1, 'email': 'customer1@gmail.com', 'city': 'Ahmedabad', 'state': 'Gujarat'}, {'customer_id': 2, 'email': 'customer2@gmail.com', 'city': 'Surat', 'state': 'Gujarat'}]

In [4]:
import requests
import pandas as pd

url = "https://jsonplaceholder.typicode.com/users"

response = requests.get(url)

api_df = pd.DataFrame(response.json())

display(api_df.head())

,id,name,username,email,address,phone,website,company
0,1,Leanne Graham,Bret,Sincere@april.biz,"{'street': 'Kulas Light', 'suite': 'Apt. 556',...",1-770-736-8031 x56442,hildegard.org,"{'name': 'Romaguera-Crona', 'catchPhrase': 'Mu..."
1,2,Ervin Howell,Antonette,Shanna@melissa.tv,"{'street': 'Victor Plains', 'suite': 'Suite 87...",010-692-6593 x09125,anastasia.net,"{'name': 'Deckow-Crist', 'catchPhrase': 'Proac..."
2,3,Clementine Bauch,Samantha,Nathan@yesenia.net,"{'street': 'Douglas Extension', 'suite': 'Suit...",1-463-123-4447,ramiro.info,"{'name': 'Romaguera-Jacobson', 'catchPhrase': ..."
3,4,Patricia Lebsack,Karianne,Julianne.OConner@kory.org,"{'street': 'Hoeger Mall', 'suite': 'Apt. 692',...",493-170-9623 x156,kale.biz,"{'name': 'Robel-Corkery', 'catchPhrase': 'Mult..."
4,5,Chelsey Dietrich,Kamren,Lucio_Hettinger@annie.ca,"{'street': 'Skiles Walks', 'suite': 'Suite 351...",(254)954-1289,demarco.info,"{'name': 'Keebler LLC', 'catchPhrase': 'User-c..."

## Part-C: Data Understanding & Cleaning

4. Explore the dataset using Pandas (.info(), .describe()).

In [5]:
Data.info()
Data.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   customer_id        5000 non-null   int64
 1   age                4750 non-null   float64
 2   gender             4850 non-null   object
 3   region             5000 non-null   object
 4   education_level    5000 non-null   object
 5   employment_type    4750 non-null   object
 6   annual_income      4700 non-null   float64
 7   loan_amount        4800 non-null   float64
 8   loan_purpose       5000 non-null   object
 9   credit_score       4750 non-null   float64
 10  repayment_history  5000 non-null   int64
 11  transaction_count  5000 non-null   int64
 12  spending_ratio     5000 non-null   float64
 13  join_date          5000 non-null   object
 14  default_flag       5000 non-null   int64
dtypes: float64(5), int64(4), object(6)
memory usage: 586.1+ KB

,customer_id,age,annual_income,loan_amount,credit_score,repayment_history,transaction_count,spending_ratio,default_flag
count,5000.000000,4750.000000,4.700000e+03,4.800000e+03,4750.000000,5000.000000,5000.00000,5000.000000,5000.000000
mean,2500.500000,45.615158,7.709522e+05,4.055845e+05,680.275832,6.067800,251.89340,52.231730,0.310800
std,1443.520003,14.466293,6.386232e+05,2.377114e+05,69.466626,3.707769,142.31751,24.711715,0.462867
min,1.000000,21.000000,5.000000e+04,1.000000e+04,415.900000,0.000000,5.00000,10.040000,0.000000
25%,1250.750000,33.000000,5.008710e+05,2.261736e+05,632.525000,3.000000,129.00000,30.800000,0.000000
50%,2500.500000,45.000000,7.047853e+05,3.996157e+05,680.500000,6.000000,252.00000,52.175000,0.000000
75%,3750.250000,58.000000,9.152051e+05,5.736819e+05,728.175000,9.000000,374.00000,73.850000,1.000000
max,5000.000000,70.000000,7.577316e+06,1.340616e+06,850.000000,12.000000,500.00000,94.990000,1.000000

5. Perfrom Pandas profiling to generate a data quality report.

In [6]:
from pandas_profiling import ProfileReport

profile = ProfileReport(Data, title="Customer Credit Risk Dataset Report")
profile.to_file("customer_credit_risk_report.html")

c:\Users\Divy\AppData\Local\Programs\Python\Python313\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
C:\Users\Divy\AppData\Local\Temp\ipykernel_10332\2324087894.py:1: DeprecationWarning: `import pandas_profiling` is going to be deprecated by April 1st. Please use `import ydata_profiling` instead.
  from pandas_profiling import ProfileReport
100%|██████████| 15/15 [00:00<00:00, 254.53it/s]<00:00, 12.49it/s, Describe variable: default_flag]
Summarize dataset: 100%|██████████| 89/89 [00:08<00:00, 10.26it/s, Completed]
Generate report structure: 100%|██████████| 1/1 [00:03<00:00,  3.88s/it]
Render HTML: 100%|██████████| 1/1 [00:02<00:00,  2.61s/it]
Export report to file: 100%|██████████| 1/1 [00:00<00:00, 36.84it/s]

In [7]:
cat_cols = ["gender", "region", "education_level",
            "employment_type", "loan_purpose"]

for col in cat_cols:
    Data[col] = Data[col].astype("category")

6. Handle missing data with:

In [16]:
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
from sklearn.impute import KNNImputer
from sklearn.impute import SimpleImputer

# 1. Simple Imputer – Numerical (Mean/Median)
df_most = Data.copy()
imputer = SimpleImputer(strategy="mean")
Data["annual_income"] = imputer.fit_transform(Data[["annual_income"]])
print(Data.head())

df_most = Data.copy()   
imputer = SimpleImputer(strategy="median")
Data["loan_amount"] = imputer.fit_transform(Data[["loan_amount"]])
print(Data.head())

# 2. Simple Imputer (Categorical: Most Frequent)
categorical_cols = Data.select_dtypes(include=["object", "category"]).columns
imputer = SimpleImputer(strategy="most_frequent")
Data[categorical_cols] = imputer.fit_transform(Data[categorical_cols])
print("Missing values after categorical imputation:")
print(Data[categorical_cols].isnull().sum())

# 3. Most Frequent Category Imputation
Data["gender"] = Data["gender"].fillna(Data["gender"].mode()[0])
print(Data["gender"].isnull().sum())

# 4. Missing Indicator + Random Sample Imputation

imputer = IterativeImputer(random_state=42)
Data[["annual_income"]] = imputer.fit_transform(Data[["annual_income"]])
print(Data.head())

# 5. KNN Imputer (Multivariate)
imputer = KNNImputer(n_neighbors=5)
Data[["annual_income"]] = imputer.fit_transform(Data[["annual_income"]])
print(Data.head())

# 6. MICE Algorithm
imputer = IterativeImputer(random_state=42)
Data[["annual_income"]] = imputer.fit_transform(Data[["annual_income"]])
print(Data.head())

# 7. Complete Case Analysis(dropping rows/columns).
Data.dropna(inplace=True)
print(Data.head())

   customer_id   age  gender region education_level employment_type  \
0            1   NaN  Female  North         Primary        Salaried
1            2   NaN  Female   East         Primary        Salaried
2            3   NaN   Other   West         Primary   Self-Employed
3            4  56.0    Male  South        Graduate        Salaried
4            5  27.0   Other  South       Secondary        Salaried

   annual_income  loan_amount loan_purpose  credit_score  repayment_history  \
0     1077610.09   664785.700          Car         700.8                 11
1      807240.03   564159.130     Business         687.7                 10
2      663601.61   399615.725         Home         734.8                  5
3      875676.45    40513.550          Car         574.6                  5
4      459448.99   587944.740     Business         714.2                 10

   transaction_count  spending_ratio   join_date  default_flag
0                461           56.36  2024-08-15             0
1                364           56.32  2020-06-21             0
2                438           39.24  2020-12-19             0
3                300           26.34  2018-10-12             1
4                141           69.65  2025-08-31             1
   customer_id   age  gender region education_level employment_type  \
0            1   NaN  Female  North         Primary        Salaried
1            2   NaN  Female   East         Primary        Salaried
2            3   NaN   Other   West         Primary   Self-Employed
3            4  56.0    Male  South        Graduate        Salaried
4            5  27.0   Other  South       Secondary        Salaried

   annual_income  loan_amount loan_purpose  credit_score  repayment_history  \
0     1077610.09   664785.700          Car         700.8                 11
1      807240.03   564159.130     Business         687.7                 10
2      663601.61   399615.725         Home         734.8                  5
3      875676.45    40513.550          Car         574.6                  5
4      459448.99   587944.740     Business         714.2                 10

   transaction_count  spending_ratio   join_date  default_flag
0                461           56.36  2024-08-15             0
1                364           56.32  2020-06-21             0
2                438           39.24  2020-12-19             0
3                300           26.34  2018-10-12             1
4                141           69.65  2025-08-31             1
Missing values after categorical imputation:
gender             0
region             0
education_level    0
employment_type    0
loan_purpose       0
join_date          0
dtype: int64
0
   customer_id   age  gender region education_level employment_type  \
0            1   NaN  Female  North         Primary        Salaried
1            2   NaN  Female   East         Primary        Salaried
2            3   NaN   Other   West         Primary   Self-Employed
3            4  56.0    Male  South        Graduate        Salaried
4            5  27.0   Other  South       Secondary        Salaried

   annual_income  loan_amount loan_purpose  credit_score  repayment_history  \
0     1077610.09   664785.700          Car         700.8                 11
1      807240.03   564159.130     Business         687.7                 10
2      663601.61   399615.725         Home         734.8                  5
3      875676.45    40513.550          Car         574.6                  5
4      459448.99   587944.740     Business         714.2                 10

   transaction_count  spending_ratio   join_date  default_flag
0                461           56.36  2024-08-15             0
1                364           56.32  2020-06-21             0
2                438           39.24  2020-12-19             0
3                300           26.34  2018-10-12             1
4                141           69.65  2025-08-31             1
   customer_id   age  gender region education_level employment_type  \
0            1   NaN  Female  North         Primary        Salaried
1            2   NaN  Female   East         Primary        Salaried
2            3   NaN   Other   West         Primary   Self-Employed
3            4  56.0    Male  South        Graduate        Salaried
4            5  27.0   Other  South       Secondary        Salaried

   annual_income  loan_amount loan_purpose  credit_score  repayment_history  \
0     1077610.09   664785.700          Car         700.8                 11
1      807240.03   564159.130     Business         687.7                 10
2      663601.61   399615.725         Home         734.8                  5
3      875676.45    40513.550          Car         574.6                  5
4      459448.99   587944.740     Business         714.2                 10

   transaction_count  spending_ratio   join_date  default_flag
0                461           56.36  2024-08-15             0
1                364           56.32  2020-06-21             0
2                438           39.24  2020-12-19             0
3                300           26.34  2018-10-12             1
4                141           69.65  2025-08-31             1
   customer_id   age  gender region education_level employment_type  \
0            1   NaN  Female  North         Primary        Salaried
1            2   NaN  Female   East         Primary        Salaried
2            3   NaN   Other   West         Primary   Self-Employed
3            4  56.0    Male  South        Graduate        Salaried
4            5  27.0   Other  South       Secondary        Salaried

   annual_income  loan_amount loan_purpose  credit_score  repayment_history  \
0     1077610.09   664785.700          Car         700.8                 11
1      807240.03   564159.130     Business         687.7                 10
2      663601.61   399615.725         Home         734.8                  5
3      875676.45    40513.550          Car         574.6                  5
4      459448.99   587944.740     Business         714.2                 10

   transaction_count  spending_ratio   join_date  default_flag
0                461           56.36  2024-08-15             0
1                364           56.32  2020-06-21             0
2                438           39.24  2020-12-19             0
3                300           26.34  2018-10-12             1
4                141           69.65  2025-08-31             1
   customer_id   age gender region education_level employment_type  \
3            4  56.0   Male  South        Graduate        Salaried
4            5  27.0  Other  South       Secondary        Salaried
5            6  45.0   Male  North        Graduate   Self-Employed
6            7  25.0  Other  South        Graduate      Unemployed
7            8  48.0  Other  South       Secondary      Unemployed

   annual_income  loan_amount loan_purpose  credit_score  repayment_history  \
3      875676.45     40513.55          Car         574.6                  5
4      459448.99    587944.74     Business         714.2                 10
5      939802.92    740480.04    Education         631.7                  3
6      874233.92    980352.13        Other         639.6                  6
7     1102267.96    258065.90     Business         709.1                  2

   transaction_count  spending_ratio   join_date  default_flag
3                300           26.34  2018-10-12             1
4                141           69.65  2025-08-31             1
5                355           37.56  2018-08-18             0
6                457           87.74  2023-02-23             1
7                265           51.95  2018-07-12             0

## Part-D: Outlier Handling

7. Detect and treat outliers using:

In [ ]:
# Z-score method
from scipy import stats

z_scores = stats.zscore(Data["annual_income"])
Data = Data[abs(z_scores) < 3]
print("Z-score", Data.head())

# IQR method
Q1 = Data["loan_amount"].quantile(0.25)
Q3 = Data["loan_amount"].quantile(0.75)
IQR = Q3 - Q1
Data = Data[(Data["loan_amount"] >= Q1 - 1.5 * IQR) & (Data["loan_amount"] <= Q3 + 1.5 * IQR)]
print("IQR", Data.head())

# Percentile method
lower_percentile = Data["loan_amount"].quantile(0.01)
upper_percentile = Data["loan_amount"].quantile(0.99)
Data = Data[(Data["loan_amount"] >= lower_percentile) & (Data["loan_amount"] <= upper_percentile)]
print("Percentile", Data.head())

# Winsorization method
from scipy.stats.mstats import winsorize

Data["loan_amount"] = winsorize(Data["loan_amount"], limits=[0.01, 0.01])
print("Winsorization", Data.head())

Z-score    customer_id   age  gender region education_level employment_type  \
0            1   NaN  Female  North         Primary        Salaried
1            2   NaN  Female   East         Primary        Salaried
2            3   NaN   Other   West         Primary   Self-Employed
3            4  56.0    Male  South        Graduate        Salaried
4            5  27.0   Other  South       Secondary        Salaried

   annual_income  loan_amount loan_purpose  credit_score  repayment_history  \
0     1077610.09   664785.700          Car         700.8                 11
1      807240.03   564159.130     Business         687.7                 10
2      663601.61   399615.725         Home         734.8                  5
3      875676.45    40513.550          Car         574.6                  5
4      459448.99   587944.740     Business         714.2                 10

   transaction_count  spending_ratio   join_date  default_flag
0                461           56.36  2024-08-15             0
1                364           56.32  2020-06-21             0
2                438           39.24  2020-12-19             0
3                300           26.34  2018-10-12             1
4                141           69.65  2025-08-31             1
IQR    customer_id   age  gender region education_level employment_type  \
0            1   NaN  Female  North         Primary        Salaried
1            2   NaN  Female   East         Primary        Salaried
2            3   NaN   Other   West         Primary   Self-Employed
3            4  56.0    Male  South        Graduate        Salaried
4            5  27.0   Other  South       Secondary        Salaried

   annual_income  loan_amount loan_purpose  credit_score  repayment_history  \
0     1077610.09   664785.700          Car         700.8                 11
1      807240.03   564159.130     Business         687.7                 10
2      663601.61   399615.725         Home         734.8                  5
3      875676.45    40513.550          Car         574.6                  5
4      459448.99   587944.740     Business         714.2                 10

   transaction_count  spending_ratio   join_date  default_flag
0                461           56.36  2024-08-15             0
1                364           56.32  2020-06-21             0
2                438           39.24  2020-12-19             0
3                300           26.34  2018-10-12             1
4                141           69.65  2025-08-31             1
Percentile    customer_id   age  gender region education_level employment_type  \
0            1   NaN  Female  North         Primary        Salaried
1            2   NaN  Female   East         Primary        Salaried
2            3   NaN   Other   West         Primary   Self-Employed
3            4  56.0    Male  South        Graduate        Salaried
4            5  27.0   Other  South       Secondary        Salaried

   annual_income  loan_amount loan_purpose  credit_score  repayment_history  \
0     1077610.09   664785.700          Car         700.8                 11
1      807240.03   564159.130     Business         687.7                 10
2      663601.61   399615.725         Home         734.8                  5
3      875676.45    40513.550          Car         574.6                  5
4      459448.99   587944.740     Business         714.2                 10

   transaction_count  spending_ratio   join_date  default_flag
0                461           56.36  2024-08-15             0
1                364           56.32  2020-06-21             0
2                438           39.24  2020-12-19             0
3                300           26.34  2018-10-12             1
4                141           69.65  2025-08-31             1
Winsorization    customer_id   age  gender region education_level employment_type  \
0            1   NaN  Female  North         Primary        Salaried
1            2   NaN  Female   East         Primary        Salaried
2            3   NaN   Other   West         Primary   Self-Employed
3            4  56.0    Male  South        Graduate        Salaried
4            5  27.0   Other  South       Secondary        Salaried

   annual_income  loan_amount loan_purpose  credit_score  repayment_history  \
0     1077610.09   664785.700          Car         700.8                 11
1      807240.03   564159.130     Business         687.7                 10
2      663601.61   399615.725         Home         734.8                  5
3      875676.45    40513.550          Car         574.6                  5
4      459448.99   587944.740     Business         714.2                 10

   transaction_count  spending_ratio   join_date  default_flag
0                461           56.36  2024-08-15             0
1                364           56.32  2020-06-21             0
2                438           39.24  2020-12-19             0
3                300           26.34  2018-10-12             1
4                141           69.65  2025-08-31             1

## Part-E: Feature Engineering

8. Handle variable types:

In [17]:
# Mixed variable (numeric + categorical)
Data["age_group"] = pd.cut(Data["age"],bins=[18, 30, 45, 60, 100],labels=["Young", "Adult", "Middle", "Senior"])

Data["region_age"] = (Data["region"].astype(str) + "_" +Data["age_group"].astype(str))

print(Data[["region", "age", "region_age"]].head())

  region   age    region_age
3  South  56.0  South_Middle
4  South  27.0   South_Young
5  North  45.0   North_Adult
6  South  25.0   South_Young
7  South  48.0  South_Middle

In [ ]:
# Date & Time variable
Data["join_date"] = pd.to_datetime(Data["join_date"], errors="coerce")

Data["year"] = Data["join_date"].dt.year
Data["month"] = Data["join_date"].dt.month
Data["day"] = Data["join_date"].dt.day
Data["weekday"] = Data["join_date"].dt.weekday

print(Data[["join_date", "year", "month", "day", "weekday"]].head())

   join_date  year  month  day  weekday
0 2024-08-15  2024      8   15        3
1 2020-06-21  2020      6   21        6
2 2020-12-19  2020     12   19        5
3 2018-10-12  2018     10   12        4
4 2025-08-31  2025      8   31        6

9. Encoding categorical variables:

In [18]:
# Ordinal Encoding
Data["education_encoded"] = Data["education_level"].astype("category").cat.codes
print(Data[["education_level", "education_encoded"]].head())

  education_level  education_encoded
3        Graduate                  0
4       Secondary                  3
5        Graduate                  0
6        Graduate                  0
7       Secondary                  3

In [19]:
# Label Encoding
Data["gender_encoded"] = Data["gender"].astype("category").cat.codes
print(Data[["gender", "gender_encoded"]].head())

  gender  gender_encoded
3   Male               1
4  Other               2
5   Male               1
6  Other               2
7  Other               2

In [20]:
# One-Hot Encoding
cat_cols = Data.select_dtypes(include=["object", "category"]).columns

Data = pd.get_dummies(Data, columns=cat_cols, drop_first=True)

print(Data.head())

   customer_id   age  annual_income  loan_amount  credit_score  \
3            4  56.0      875676.45     40513.55         574.6
4            5  27.0      459448.99    587944.74         714.2
5            6  45.0      939802.92    740480.04         631.7
6            7  25.0      874233.92    980352.13         639.6
7            8  48.0     1102267.96    258065.90         709.1

   repayment_history  transaction_count  spending_ratio  default_flag  \
3                  5                300           26.34             1
4                 10                141           69.65             1
5                  3                355           37.56             0
6                  6                457           87.74             1
7                  2                265           51.95             0

   education_encoded  ...  region_age_North_Senior  region_age_North_Young  \
3                  0  ...                    False                   False
4                  3  ...                    False                   False
5                  0  ...                    False                   False
6                  0  ...                    False                   False
7                  3  ...                    False                   False

   region_age_South_Adult  region_age_South_Middle  region_age_South_Senior  \
3                   False                     True                    False
4                   False                    False                    False
5                   False                    False                    False
6                   False                    False                    False
7                   False                     True                    False

   region_age_South_Young  region_age_West_Adult  region_age_West_Middle  \
3                   False                  False                   False
4                    True                  False                   False
5                   False                  False                   False
6                    True                  False                   False
7                   False                  False                   False

   region_age_West_Senior  region_age_West_Young
3                   False                  False
4                   False                  False
5                   False                  False
6                   False                  False
7                   False                  False

[5 rows x 2276 columns]

10. Encoding numerical features:

In [21]:
# Binning(discretize income into groups)
Data["income_binned"] = pd.cut(Data["annual_income"], bins=5, labels=False)
print(Data[["annual_income", "income_binned"]].head())

   annual_income  income_binned
3      875676.45              0
4      459448.99              0
5      939802.92              0
6      874233.92              0
7     1102267.96              0

In [22]:
# Binarization (flag if>threshold)
Data["income_flag"] = (Data["annual_income"] > Data["annual_income"].median()).astype(int)
print(Data[["annual_income", "income_flag"]].head())

   annual_income  income_flag
3      875676.45            1
4      459448.99            0
5      939802.92            1
6      874233.92            1
7     1102267.96            1

In [23]:
# Quantile Binning
Data["income_quantile"] = pd.qcut(Data["annual_income"], q=5, labels=False, duplicates="drop")
print(Data[["annual_income", "income_quantile"]].head())

   annual_income  income_quantile
3      875676.45                3
4      459448.99                1
5      939802.92                3
6      874233.92                3
7     1102267.96                4

In [24]:
# K-Means Binning
from sklearn.cluster import KMeans

kmeans = KMeans(n_clusters=5, random_state=42)
Data["income_kmeans"] = kmeans.fit_predict(Data[["annual_income"]])
print(Data[["annual_income", "income_kmeans"]].head())

   annual_income  income_kmeans
3      875676.45              4
4      459448.99              0
5      939802.92              3
6      874233.92              4
7     1102267.96              3

## Part-F: Feature Scaling

11. Apply multiple scaling methods:

In [25]:
# Standardization(Z-score scaling)
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
Data["annual_income_scaled"] = scaler.fit_transform(Data[["annual_income"]])
print(Data[["annual_income", "annual_income_scaled"]].head())

   annual_income  annual_income_scaled
3      875676.45              0.173310
4      459448.99             -0.506862
5      939802.92              0.278101
6      874233.92              0.170952
7     1102267.96              0.543591

In [26]:
# Normalization
from sklearn.preprocessing import MinMaxScaler

minmax_scaler = MinMaxScaler()
Data["annual_income_normalized"] = minmax_scaler.fit_transform(Data[["annual_income"]])
print(Data[["annual_income", "annual_income_normalized"]].head())

   annual_income  annual_income_normalized
3      875676.45                  0.109691
4      459448.99                  0.054395
5      939802.92                  0.118210
6      874233.92                  0.109499
7     1102267.96                  0.139793

In [27]:
# Min-Max Scaling
from sklearn.preprocessing import MinMaxScaler

minmax_scaler = MinMaxScaler()
Data["annual_income_minmax"] = minmax_scaler.fit_transform(Data[["annual_income"]])
print(Data[["annual_income", "annual_income_minmax"]].head())

   annual_income  annual_income_minmax
3      875676.45              0.109691
4      459448.99              0.054395
5      939802.92              0.118210
6      874233.92              0.109499
7     1102267.96              0.139793

In [28]:
# MaxAbs Scaling
from sklearn.preprocessing import MaxAbsScaler

maxabs_scaler = MaxAbsScaler()
Data["annual_income_maxabs"] = maxabs_scaler.fit_transform(Data[["annual_income"]])
print(Data[["annual_income", "annual_income_maxabs"]].head())

   annual_income  annual_income_maxabs
3      875676.45              0.115566
4      459448.99              0.060635
5      939802.92              0.124028
6      874233.92              0.115375
7     1102267.96              0.145469

In [29]:
# Robust Scaling
from sklearn.preprocessing import RobustScaler
robust_scaler = RobustScaler()
Data["annual_income_robust"] = robust_scaler.fit_transform(Data[["annual_income"]])
print(Data[["annual_income", "annual_income_robust"]].head())

   annual_income  annual_income_robust
3      875676.45              0.383347
4      459448.99             -0.690580
5      939802.92              0.548803
6      874233.92              0.379625
7     1102267.96              0.967986

## Part-G: Feature Construction & Transformation

12. Apply transformations:

In [30]:
# FunctionTransformer (Log Transformation,reciprocal,square root)
from sklearn.preprocessing import FunctionTransformer
import numpy as np
log_transformer = FunctionTransformer(func=np.log1p, inverse_func=np.expm1)
Data["annual_income_log"] = log_transformer.fit_transform(Data[["annual_income"]])
reciprocal_transformer = FunctionTransformer(func=np.reciprocal, inverse_func=np.reciprocal)
Data["annual_income_reciprocal"] = reciprocal_transformer.fit_transform(Data[["annual_income"]])
sqrt_transformer = FunctionTransformer(func=np.sqrt, inverse_func=np.square)
Data["annual_income_sqrt"] = sqrt_transformer.fit_transform(Data[["annual_income"]])
print(Data[["annual_income", "annual_income_log", "annual_income_reciprocal", "annual_income_sqrt"]].head())

   annual_income  annual_income_log  annual_income_reciprocal  \
3      875676.45          13.682753              1.141974e-06
4      459448.99          13.037785              2.176520e-06
5      939802.92          13.753427              1.064053e-06
6      874233.92          13.681104              1.143859e-06
7     1102267.96          13.912881              9.072204e-07

   annual_income_sqrt
3          935.775855
4          677.826667
5          969.434330
6          935.004770
7         1049.889499

In [31]:
# PowerTransformer (Box-Cox Transformation,Yeo-Johnson Transformation)
from sklearn.preprocessing import PowerTransformer

box_cox_transformer = PowerTransformer(method='box-cox')
Data["annual_income_boxcox"] = box_cox_transformer.fit_transform(Data[["annual_income"]])

yeo_johnson_transformer = PowerTransformer(method='yeo-johnson')
Data["annual_income_yeojohnson"] = yeo_johnson_transformer.fit_transform(Data[["annual_income"]])
print(Data[["annual_income", "annual_income_boxcox", "annual_income_yeojohnson"]].head())

   annual_income  annual_income_boxcox  annual_income_yeojohnson
3      875676.45              0.469466                  0.469466
4      459448.99             -0.621889                 -0.621889
5      939802.92              0.597812                  0.597812
6      874233.92              0.466493                  0.466494
7     1102267.96              0.894120                  0.894120

In [32]:
# Column Transformer (apply different preprocessing steps to different columns).
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import PowerTransformer

column_transformer = ColumnTransformer(
    transformers=[
        ('boxcox', PowerTransformer(method='box-cox'), ['annual_income']),
        ('yeojohnson', PowerTransformer(method='yeo-johnson'), ['annual_income'])
    ]
)

df = column_transformer.fit_transform(Data)
print(df)

[[ 0.46946592  0.46946633]
 [-0.62188883 -0.6218892 ]
 [ 0.59781159  0.59781204]
 ...
 [-2.07203941 -2.07204101]
 [ 0.97781024  0.97781074]
 [ 0.55421646  0.55421691]]

13.  Construct new features:

In [ ]:
# Debt-to-Income ratio.
Data["debt_to_income_ratio"] = Data["loan_amount"] / Data["annual_income"]
print(Data[["loan_amount", "annual_income", "debt_to_income_ratio"]].head())

   loan_amount  annual_income  debt_to_income_ratio
0    664785.70     1077610.09              0.616907
1    564159.13      807240.03              0.698874
2          NaN      663601.61                   NaN
3     40513.55      875676.45              0.046265
4    587944.74      459448.99              1.279674

In [56]:
# Average monthly transaction.
Data["avg_transaction"] = (Data["spending_ratio"] / Data["transaction_count"])
print(Data[["spending_ratio","transaction_count","avg_transaction"]].head())

   spending_ratio  transaction_count  avg_transaction
3           26.34                300         0.087800
4           69.65                141         0.493972
5           37.56                355         0.105803
6           87.74                457         0.191991
7           51.95                265         0.196038

In [57]:
# Spending-to-Income ratio.
Data["spending_to_income_ratio"] = Data["spending_ratio"] / Data["annual_income"]
print(Data[["spending_ratio", "annual_income", "spending_to_income_ratio"]].head())

   spending_ratio  annual_income  spending_to_income_ratio
3           26.34      875676.45                  0.000030
4           69.65      459448.99                  0.000152
5           37.56      939802.92                  0.000040
6           87.74      874233.92                  0.000100
7           51.95     1102267.96                  0.000047

## Part-H: Final Deliverable

14. Provide a final cleaned and transformed dataset.

In [ ]:

final_data = Data.copy()

print("Final Dataset Shape:", final_data.shape)
print("\nFinal Dataset:")
print(final_data.head())

print("\nMissing Values:")
print(final_data.isnull().sum())

print("\nData Types:")
print(final_data.dtypes)

final_data.to_csv("final_cleaned_transformed_dataset.csv", index=False)

print("\nFinal cleaned and transformed dataset saved successfully!")

Final Dataset Shape: (4513, 2292)

Final Dataset:
   customer_id   age  annual_income  loan_amount  credit_score  \
3            4  56.0      875676.45     40513.55         574.6
4            5  27.0      459448.99    587944.74         714.2
5            6  45.0      939802.92    740480.04         631.7
6            7  25.0      874233.92    980352.13         639.6
7            8  48.0     1102267.96    258065.90         709.1

   repayment_history  transaction_count  spending_ratio  default_flag  \
3                  5                300           26.34             1
4                 10                141           69.65             1
5                  3                355           37.56             0
6                  6                457           87.74             1
7                  2                265           51.95             0

   education_encoded  ...  annual_income_minmax  annual_income_maxabs  \
3                  0  ...              0.109691              0.115566
4                  3  ...              0.054395              0.060635
5                  0  ...              0.118210              0.124028
6                  0  ...              0.109499              0.115375
7                  3  ...              0.139793              0.145469

   annual_income_robust  annual_income_log  annual_income_reciprocal  \
3              0.383347          13.682753              1.141974e-06
4             -0.690580          13.037785              2.176520e-06
5              0.548803          13.753427              1.064053e-06
6              0.379625          13.681104              1.143859e-06
7              0.967986          13.912881              9.072204e-07

   annual_income_sqrt  annual_income_boxcox  annual_income_yeojohnson  \
3          935.775855              0.469466                  0.469466
4          677.826667             -0.621889                 -0.621889
5          969.434330              0.597812                  0.597812
6          935.004770              0.466493                  0.466494
7         1049.889499              0.894120                  0.894120

   spending_to_income_ratio  avg_transaction
3                  0.000030         0.087800
4                  0.000152         0.493972
5                  0.000040         0.105803
6                  0.000100         0.191991
7                  0.000047         0.196038

[5 rows x 2292 columns]

Missing Values:
customer_id                 0
age                         0
annual_income               0
loan_amount                 0
credit_score                0
                           ..
annual_income_sqrt          0
annual_income_boxcox        0
annual_income_yeojohnson    0
spending_to_income_ratio    0
avg_transaction             0
Length: 2292, dtype: int64

Data Types:
customer_id                   int64
age                         float64
annual_income               float64
loan_amount                 float64
credit_score                float64
                             ...
annual_income_sqrt          float64
annual_income_boxcox        float64
annual_income_yeojohnson    float64
spending_to_income_ratio    float64
avg_transaction             float64
Length: 2292, dtype: object

Final cleaned and transformed dataset saved successfully!

15. Write a report summarizing:

1. Missing Value Strategies Used and Their Effectiveness:

- Missing values were identified using isnull().sum().
- For **numerical variables**, missing values were handled using the **median**, as the median is less affected by outliers.
- For **categorical variables**, missing values were replaced using the **mode**.

- These methods successfully reduced missing values while preserving the useful information in the dataset. The final dataset was checked again to ensure that missing values were properly handled.

2. Outlier Handling Results:

- Outliers were detected using the **IQR (Interquartile Range) method**.

- The IQR was calculated as:

- **IQR = Q3 − Q1**

- Values below Q1 − 1.5 × IQR or above Q3 + 1.5 × IQR were considered potential outliers.

- Outliers were handled by **capping extreme values within the acceptable IQR limits**. This reduced the influence of extreme observations without unnecessarily deleting records.

3. Encoding Methods Applied:

- **Label Encoding**: Used for ordinal variables where there is a natural ordering (e.g., education level: High School, Bachelor, Master, PhD).

- **One-Hot Encoding**: Used for nominal variables where there is no inherent order (e.g., gender, city).

4. Scaling and Transformations Applied:

- **Standardization (Z-score normalization)**: Applied to numerical features to ensure they have a mean of 0 and a standard deviation of 1. This is particularly useful for algorithms that assume normally distributed data.

- **Min-Max Scaling**: Applied to features that need to be scaled to a specific range (e.g., [0, 1]). This is useful for algorithms that are sensitive to the scale of input data.

- **Box-Cox Transformation**: Applied to stabilize variance and make the data more normally distributed. This is particularly useful for features that are not normally distributed.

- **Yeo-Johnson Transformation**: Applied to stabilize variance and make the data more normally distributed. This is particularly useful for features that are not normally distributed.

5. Newly Engineered Features and Their Usefulness:

- **Interaction Features**: Created by combining two or more features to capture relationships between them (e.g., Age * Income).

- **Polynomial Features**: Created by raising features to a power (e.g., Age^2) to capture non-linear relationships.

- **Binning**: Continuous variables were binned into categories (e.g., Age groups: 18-25, 26-35, etc.) to reduce the effect of outliers and improve model interpretability.

6. Final Dataset Shape and Readiness for ML Modeling:

- The final dataset shape was (n_samples, n_features), where n_samples is the number of records and n_features is the number of features after preprocessing.

- The dataset was free of missing values, outliers were handled, categorical variables were encoded, and numerical features were scaled and transformed as necessary.

- The dataset was now ready for machine learning modeling, ensuring that the data quality and integrity were maintained throughout the preprocessing steps.